<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <RuntimeIdentifiers>win-x64;linux-x64;osx-x64</RuntimeIdentifiers>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Assets\app-icon.ico</ApplicationIcon>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <Version>0.0.0-PLACEHOLDER</Version>
        <PackageId>rmOneNoteSyncApp</PackageId>
        <PackageTags>rmOneNoteSync;reMarkable;OneNote;sync;notebook</PackageTags>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Excustic/rmOneNoteSync</PackageProjectUrl>
        <RepositoryUrl>https://github.com/Excustic/rmOneNoteSync</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <Authors>excustic</Authors>
        <Description>Synchronize reMarkable notebooks to OneNote</Description>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <PropertyGroup>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="licenses\LICENSE.txt" Pack="true" PackagePath=""/>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
        <Content Include="rmc-x64.exe" Link="rmc.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <Content Include="rmc-linux-x64" Link="rmc">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Assets\rmOneNoteSync.desktop">
            <LinuxPath>/usr/share/applications/rmOneNoteSync.desktop</LinuxPath>
        </Content>
        <Content Include="Assets\rmOneNoteSync.desktop">
            <LinuxPath>/etc/xdg/autostart/rmOneNoteSync.desktop</LinuxPath>
        </Content>
        <Content Include="Assets\app-icon.png">
            <LinuxPath>/usr/share/icons/hicolor/256x256/apps/rmOneNoteSyncApp.png</LinuxPath>
        </Content>
        <!-- DEB / RPM support-->
        <LinuxPackageItem Include="Assets\rmOneNoteSync.desktop">
            <InstallPath>/usr/share/applications/rmOneNoteSync.desktop</InstallPath>
        </LinuxPackageItem>
        <LinuxPackageItem Include="Assets\rmOneNoteSync.desktop">
            <InstallPath>/etc/xdg/autostart/rmOneNoteSync.desktop</InstallPath>
        </LinuxPackageItem>
        <LinuxPackageItem Include="Assets\app-icon.png">
            <InstallPath>/usr/share/icons/hicolor/256x256/apps/rmOneNoteSyncApp.png</InstallPath>
        </LinuxPackageItem>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.4" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.4" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.4" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.4" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.4" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.4">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Azure.Identity" Version="1.16.0" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
        <PackageReference Include="DynamicData" Version="9.4.1" />
        <PackageReference Include="Material.Avalonia" Version="3.13.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
        <PackageReference Include="Microsoft.Graph" Version="5.92.0" />
        <PackageReference Include="Microsoft.Graph.Core" Version="3.2.4" />
        <PackageReference Include="Microsoft.Identity.Client" Version="4.76.0" />
        <PackageReference Include="Packaging.Targets" Version="0.1.232">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Serilog" Version="4.3.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SharpPcap" Version="6.3.1" />
        <PackageReference Include="SSH.NET" Version="2024.0.0" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
        <PackageReference Include="Dapper" Version="2.1.35" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.8" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
        <PackageReference Include="System.Management" Version="10.0.0-preview.7.25380.108" />
        <PackageReference Include="Xaml.Behaviors.Avalonia" Version="11.3.2" />
    </ItemGroup>
</Project>
