using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using rmOneNoteSyncApp.Services.Interfaces;

namespace rmOneNoteSyncApp.Services;

public class ConfigurationProviderService(
    ILogger<ConfigurationProviderService> logger,
    IDatabaseService databaseService,
    ISshService sshService,
    IDeviceDetectionService deviceDetectionService)
    : IConfigurationProviderService
{
    private const string RemarkableIp = AppSettings.DefaultDeviceIp;
    public const string ConfigPath = "/home/root/onenote-sync/daemon.conf";
    private static readonly JsonSerializerOptions _jsonOptions = new() { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    string IConfigurationProviderService.ConfigPath => ConfigPath;

    public async Task<string> GetConfigurationJsonAsync(string deviceId)
    {
        var config = await databaseService.GetConfigurationAsync();

        // Get the host IP address that's accessible from the reMarkable
        var hostIp = await deviceDetectionService.GetLocalIpAddressForDevice(RemarkableIp);
        int serverPort = config?.SyncServerPort ?? AppSettings.DefaultServerPort;

        // Build configuration for the device
        var deviceConfig = new
        {
            server_url = $"http://{hostIp}:{serverPort}/upload",
            api_key = string.Concat("rmOneNoteSync-", Guid.NewGuid().ToString("N").AsSpan(0, 16)),
            whitelist_ids = config?.SyncFiles ?? [], // New field with file IDs
            upload_interval_seconds = config?.SyncIntervalSeconds ?? 300,
            max_retries = config?.MaxRetries ?? 3,
            retry_delay_seconds = config?.RetryDelaySeconds ?? 5,
            timeout_seconds = config?.TimeoutSeconds ?? 10,
            device_id = deviceId,
            timestamp = DateTime.UtcNow.ToString("O"),
            version = "2.0" // Version 2 uses whitelist instead of path filtering
        };

        return JsonSerializer.Serialize(deviceConfig, _jsonOptions);
    }

    public async Task<bool> UpdateDeviceConfigurationAsync(bool restartService = true)
    {
        try
        {
            var config = await databaseService.GetConfigurationAsync();
            int serverPort = config?.SyncServerPort ?? AppSettings.DefaultServerPort;

            // Step 1: Resolve correct host IP
            var hostIp = await deviceDetectionService.GetLocalIpAddressForDevice(RemarkableIp) ?? "127.0.0.1";
            var hostIpFallback = await deviceDetectionService.GetLocalIpAddressForDevice(
                deviceDetectionService.CurrentDevice?.IpAddress ?? string.Empty) ?? "127.0.0.1";
            logger.LogDebug("Using host IP: {IP} for reMarkable communication", hostIp);

            // Step 2: Build whitelist
            var syncFileIds = config?.SyncFiles ?? [];
            var rmSubnet = RemarkableIp[..RemarkableIp.LastIndexOf('.')];
            logger.LogDebug("Updating reMarkable with {Count} document IDs to sync", syncFileIds.Count);

            // Step 3: Fetch existing config to merge endpoints
            var deviceIp = deviceDetectionService.CurrentDevice?.IpAddress ?? RemarkableIp;
            var configUrl = $"http://{deviceIp}:8000/config";
            var existingEndpoints = new HashSet<string>();

            // The timeout is set here initially to avoid InvalidOperationException later
            using var httpClient = new HttpClient { Timeout = TimeSpan.FromSeconds(10) };
            try
            {
                var existingConfig = await httpClient.GetStringAsync(configUrl);
                foreach (var line in existingConfig.Split('\n', StringSplitOptions.RemoveEmptyEntries))
                {
                    if (line.StartsWith("SERVER_URL") && line.Contains('='))
                    {
                        var url = line[(line.IndexOf('=') + 1)..].Trim();
                        if (!string.IsNullOrEmpty(url)) existingEndpoints.Add(url);
                    }
                }
            }
            catch (Exception ex)
            {
                logger.LogDebug(ex, "Could not fetch existing config from {Url}. Starting fresh.", configUrl);
            }

            var primaryEndpoint = $"http://{(hostIp[..hostIp.LastIndexOf('.')].Equals(rmSubnet) ? hostIp : string.Join('.', rmSubnet, "2"))}:{serverPort}/upload";
            var fallbackEndpoint = $"http://{hostIpFallback}:{serverPort}/upload";
            existingEndpoints.Add(primaryEndpoint);
            existingEndpoints.Add(fallbackEndpoint);

            // Step 4: Build daemon.conf content (with values from persisted config)
            var configBuilder = new StringBuilder();
            configBuilder.AppendLine("# Auto-generated by rmOneNoteSyncApp");
            configBuilder.AppendLine($"# Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Server Configuration");

            int endpointIndex = 0;
            foreach (var ep in existingEndpoints)
            {
                configBuilder.AppendLine($"SERVER_URL_{endpointIndex}={ep}");
                endpointIndex++;
            }

            configBuilder.AppendLine("API_KEY=rmOneNoteSync");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Upload Settings");
            configBuilder.AppendLine($"UPLOAD_INTERVAL={config?.SyncIntervalSeconds ?? 300}");
            configBuilder.AppendLine($"MAX_RETRIES={config?.MaxRetries ?? 3}");
            configBuilder.AppendLine($"RETRY_DELAY={config?.RetryDelaySeconds ?? 5}");
            configBuilder.AppendLine($"TIMEOUT={config?.TimeoutSeconds ?? 10}");
            configBuilder.AppendLine($"AUTO_ADD_NEW_FILES={(config?.AutoAddNewFiles == true ? "1" : "0")}");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Document Whitelist");
            configBuilder.AppendLine($"WHITELIST_COUNT={syncFileIds.Count}");
            for (int i = 0; i < syncFileIds.Count; i++)
                configBuilder.AppendLine($"WHITELIST_{i}={syncFileIds[i]}");

            var syncFolders = config?.SyncFolders ?? [];
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Sync Folders");
            configBuilder.AppendLine($"SYNC_FOLDER_COUNT={syncFolders.Count}");
            for (int i = 0; i < syncFolders.Count; i++)
                configBuilder.AppendLine($"SYNC_FOLDER_{i}={syncFolders[i]}");

            // Step 5: Post config to device via HTTP (non-SSH)
            logger.LogDebug("Posting config to {Url}", configUrl);

            var content = new StringContent(configBuilder.ToString(), Encoding.UTF8, "text/plain");
            var response = await httpClient.PostAsync(configUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                logger.LogWarning("HTTP config POST failed ({Status}). Falling back to SSH.", response.StatusCode);
                // Fallback: use SSH if HTTP POST failed (e.g. old daemon without /config endpoint)
                if (sshService.IsConnected)
                {
                    var tempPath = "/tmp/daemon.conf.tmp";
                    await sshService.ExecuteCommandAsync($"cat > {tempPath} << 'CONF'\n{configBuilder}\nCONF");
                    await sshService.ExecuteCommandAsync($"mv {tempPath} {ConfigPath}");
                    logger.LogDebug("Config written via SSH fallback");
                }
                else
                {
                    logger.LogError("HTTP POST failed and SSH is not connected. Cannot update config.");
                    return false;
                }
            }
            else
            {
                logger.LogDebug("Config posted via HTTP successfully.");
            }

            // Step 5: Restart via SSH if requested
            if (restartService && sshService.IsConnected)
            {
                logger.LogDebug("Restarting httpclient service to apply new configuration");
                await sshService.ExecuteCommandAsync("systemctl restart onenote-sync-httpclient");
                await Task.Delay(2000);
                var serviceStatus = await sshService.ExecuteCommandAsync("systemctl is-active onenote-sync-httpclient");
                if (serviceStatus.Trim() == "active")
                {
                    logger.LogDebug("✅ Configuration updated and service restarted (IP:{IP}:{Port})", hostIp, serverPort);
                    return true;
                }
                logger.LogWarning("⚠️ Service may not have started correctly. Status: {Status}", serviceStatus);
                return false;
            }

            logger.LogInformation("✅ Configuration updated via HTTP (IP:{IP}:{Port})", hostIp, serverPort);
            return true;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to update reMarkable configuration");
            return false;
        }
    }

    public async Task<int> GetServerPortAsync()
    {
        var config = await databaseService.GetConfigurationAsync();
        return config?.SyncServerPort ?? AppSettings.DefaultServerPort;
    }
}