using System;
using System.Collections.Generic;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using rmOneNoteSyncApp.Services.Interfaces;

namespace rmOneNoteSyncApp.Services;

public class ConfigurationProviderService(
    ILogger<ConfigurationProviderService> logger,
    IDatabaseService databaseService,
    ISshService sshService,
    IDeviceDetectionService deviceDetectionService)
    : IConfigurationProviderService
{
    private const string RemarkableIp = "10.11.99.1";
    private const int ServerPort = 8080;
    public const string ConfigPath = "/home/root/onenote-sync/httpclient.conf";
    private static readonly JsonSerializerOptions _jsonOptions = new() { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    string IConfigurationProviderService.ConfigPath => ConfigPath;

    public async Task<string> GetConfigurationJsonAsync(string deviceId)
    {
        var config = await databaseService.GetConfigurationAsync();

        // Get the host IP address that's accessible from the reMarkable
        var hostIp = await deviceDetectionService.GetLocalIpAddressForDevice(RemarkableIp);

        // Build configuration for the device
        var deviceConfig = new
        {
            server_url = $"http://{hostIp}:{ServerPort}/upload",
            api_key = string.Concat("rmOneNoteSync-", Guid.NewGuid().ToString("N").AsSpan(0, 16)),
            whitelist_ids = config?.SyncFiles ?? [], // New field with file IDs
            upload_interval_seconds = config?.SyncIntervalSeconds ?? 300,
            max_retries = config?.MaxRetries ?? 5,
            retry_delay_seconds = config?.RetryDelaySeconds ?? 20,
            timeout_seconds = 10,
            device_id = deviceId,
            timestamp = DateTime.UtcNow.ToString("O"),
            version = "2.0" // Version 2 uses whitelist instead of path filtering
        };

        return JsonSerializer.Serialize(deviceConfig, _jsonOptions);
    }

    public async Task<bool> UpdateDeviceConfigurationAsync(bool restartService = true)
    {
        if (!sshService.IsConnected)
        {
            logger.LogWarning("Cannot update reMarkable configuration - not connected");
            return false;
        }

        try
        {
            var config = await databaseService.GetConfigurationAsync();
            // Step 1: Get the correct IP address for communication
            var hostIp = await deviceDetectionService.GetLocalIpAddressForDevice(RemarkableIp);
            var hostIpFallback = await deviceDetectionService.GetLocalIpAddressForDevice(deviceDetectionService.CurrentDevice?.IpAddress ?? string.Empty);
            logger.LogDebug("Using host IP: {IP} for reMarkable communication", hostIp);

            // Step 2: Get the whitelist of document IDs from database
            var syncFileIds = config?.SyncFiles ?? [];
            var rmSubnet = RemarkableIp[..RemarkableIp.LastIndexOf('.')];
            logger.LogDebug("Updating reMarkable with {Count} document IDs to sync", syncFileIds.Count);

            // Step 3: Build the httpclient.conf content
            var configBuilder = new StringBuilder();
            configBuilder.AppendLine("# Auto-generated by rmOneNoteSyncApp");
            configBuilder.AppendLine($"# Generated at: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Server Configuration");
            configBuilder.AppendLine($"SERVER_URL=http://{(hostIp[..hostIp.LastIndexOf('.')].Equals(rmSubnet) ? hostIp : string.Join('.', rmSubnet, "2"))}:{ServerPort}/upload");
            configBuilder.AppendLine($"SERVER_URL_FALLBACK=http://{hostIpFallback}:{ServerPort}/upload");
            configBuilder.AppendLine("API_KEY=rmOneNoteSync");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Upload Settings");
            configBuilder.AppendLine($"UPLOAD_INTERVAL={config?.SyncIntervalSeconds ?? 300}");
            configBuilder.AppendLine("MAX_RETRIES=5");
            configBuilder.AppendLine("RETRY_DELAY=20");
            configBuilder.AppendLine("TIMEOUT=10");
            configBuilder.AppendLine();
            configBuilder.AppendLine("# Document Whitelist");
            configBuilder.AppendLine($"WHITELIST_COUNT={syncFileIds.Count}");

            // Add each document ID to the whitelist
            for (int i = 0; i < syncFileIds.Count; i++)
            {
                configBuilder.AppendLine($"WHITELIST_{i}={syncFileIds[i]}");
            }

            // Step 4: Write the configuration to the reMarkable
            var tempPath = "/tmp/httpclient.conf.tmp";

            // First write to temp file to avoid corruption
            var command = $"""
                           cat > {tempPath} << 'EOF'
                           {configBuilder}
                           EOF
                           """;

            await sshService.ExecuteCommandAsync(command);

            // Verify the file was written correctly
            var verification = await sshService.ExecuteCommandAsync($"wc -l {tempPath}");
            logger.LogDebug("Config file written, lines: {Lines}", verification);

            // Move temp file to actual location
            await sshService.ExecuteCommandAsync($"mv {tempPath} {ConfigPath}");

            // Step 5: Restart the service to apply new configuration
            if (restartService)
            {
                logger.LogDebug("Restarting httpclient service to apply new configuration");
                await sshService.ExecuteCommandAsync("systemctl restart onenote-sync-httpclient");

                // Give service time to restart
                await Task.Delay(2000);

                // Verify service is running
                var serviceStatus = await sshService.ExecuteCommandAsync("systemctl is-active onenote-sync-httpclient");
                if (serviceStatus.Trim() == "active")
                {
                    logger.LogDebug("✅ Configuration updated successfully! reMarkable will send files to {IP}:{Port}",
                        hostIp, ServerPort);
                    return true;
                }
                else
                {
                    logger.LogWarning("⚠️ Service may not have started correctly. Status: {Status}", serviceStatus);
                    return false;
                }
            }

            logger.LogInformation("✅ Configuration file updated successfully without restarting service (IP: {IP}:{Port})", hostIp, ServerPort);
            return true;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to update reMarkable configuration");
            return false;
        }
    }

    public int GetServerPort() => ServerPort;
}